# Generated by Django 6.0.5 on 2026-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
